

runner:
  _target_: SSDDetectionRunner

engine:
  _target_: DeviceEngine

model:
  _target_: SingleShotDetector
  num_classes: &num_classes 5

loggers:
  console:
    _target_: ConsoleLogger

stages:
  initial_training:
    num_epochs: 100

    loaders: &loaders
      batch_size: 32
      num_workers: 4
      
      datasets:
        train:
          _target_: DetectionDataset
          coco_json_path: path/to/coco.json
          images_dir: path/to/images
          transforms:
            _target_: albumentations.Compose
            transforms:
              - _target_: albu.Resize
                height: 300
                width: 300
              - _target_: albu.Normalize
              - _target_: albu.ToTensorV2
            bbox_params:
              _target_: albu.BboxParams
              format: albumentations

        valid:
          _target_: DetectionDataset
          coco_json_path: path/to/coco.json
          images_dir: path/to/images
          transforms:
            _target_: albumentations.Compose
            transforms:
              - _target_: albu.Resize
                height: 300
                width: 300
              - _target_: albu.Normalize
              - _target_: albu.ToTensorV2
            bbox_params:
              _target_: albu.BboxParams
              format: albumentations

    criterion:
      _target_: SSDCriterion
      num_classes: 6  # +1 class (background)
      ignore_class: 0

    optimizer:
      _target_: AdamW
      lr: 0.001

    callbacks: &callbacks
      periodic_validation:
        _target_: PeriodicLoaderCallback
        valid_loader_key: valid
        valid_metric_key: mAP
        minimize: False
        valid: 10

      mAP:
        _target_: DetectionMeanAveragePrecision
        num_classes: *num_classes
        output_type: ssd

      optimizer:
        _target_: OptimizerCallback
        metric_key: loss
